# Generated by Django 2.2.6 on 2020-01-14 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ManyToManyField(to='account.Permission')),
                ('user', models.ForeignKey(on_delete=models.Model, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Role')),
                ('title', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='base.College')),
                ('subjects', models.ManyToManyField(to='base.Subject')),
            ],
            bases=('account.role',),
        ),
        migrations.CreateModel(
            name='PastDirector',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Role')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_directors', to='base.College')),
            ],
            bases=('account.role',),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Role')),
                ('name', models.CharField(max_length=80)),
                ('college', models.ManyToManyField(related_name='moderators', to='base.College')),
            ],
            bases=('account.role',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Role')),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='base.College')),
            ],
            bases=('account.role',),
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Role')),
                ('name', models.CharField(max_length=80)),
                ('college', models.ForeignKey(on_delete=models.Model, to='base.College')),
            ],
            bases=('account.role',),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Role')),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='base.College')),
            ],
            bases=('account.role',),
        ),
    ]
