# Generated by Django 2.2.6 on 2020-01-15 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professor',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='base.College'),
        ),
        migrations.AddField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(to='base.Subject'),
        ),
        migrations.AddField(
            model_name='pastdirector',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_directors', to='base.College'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='college',
            field=models.ManyToManyField(related_name='moderators', to='base.College'),
        ),
        migrations.AddField(
            model_name='director',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='base.College'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='college',
            field=models.ForeignKey(on_delete=models.Model, to='base.College'),
        ),
        migrations.AddField(
            model_name='admin',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='base.College'),
        ),
    ]
